### ISSUE TITLE
How to init Y?

### ISSUE THREAD

**Issue by EagleYing** [mfulford/DeepFM#1]
```
one_hot = True
X = np.array([
        [0,0,1, 0,0,1, 0,1, 0,1, 1,0],
        [1,0,0, 0,0,0, 1,0, 1,0, 1,0],
        [0,1,0, 1,0,0, 0,1, 0,0, 0,1]
    ])
Y = np.array([[2], [1], [3]])
field_lengths = {0:3, 1:3, 2:2, 3:2, 4:2}
len_input = sum(field_lengths.values())
inputTensor = Input(shape=(len_input,))
print(inputTensor)


# Return concatenated deep and FM embeddings when fm = True and deep = True:
deepFM_embed = LayerDeepFM(field_lengths, one_hot=one_hot, embedding_size=10, deepHidenLayers=[50, 50],
                            deep=True, fm=True, return_embedding=True, input_shape=(len_input,))(inputTensor)

print(deepFM_embed)

num_classes = 3
out = Dense(num_classes, activation="softmax", trainable=True)(deepFM_embed) 
print(out)

model = Model(inputTensor, out) 
model.compile(loss='categorical_crossentropy', optimizer='adam')

model.fit(X, Y, epochs=1, batch_size = 3)
```

cause error: ValueError: Error when checking target: expected dense_1 to have shape (3,) but got array with shape (1,)

**Comment by mfulford** [comment]
Y must either be a) 1 hot encoded or b) you should use sparse_categorical_crossentropy

a)
Y = np.array([[0], [1], [2]])
num_classes = 3
out = Dense(num_classes, activation="softmax", trainable=True)(deepFM_embed)
model.compile(loss='categorical_crossentropy', optimizer='adam')
y = to_categorical(Y)
model.fit(X, y, epochs=1, batch_size = 3)


b)
Y = np.array([[0], [1], [2]])
num_classes = 3
out = Dense(num_classes, activation="softmax", trainable=True)(deepFM_embed)
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
model.fit(X, Y, epochs=1, batch_size = 3)

**Comment by EagleYing** [comment]
> Y must either be a) 1 hot encoded or b) you should use sparse_categorical_crossentropy
> 
> a)
> Y = np.array([[0], [1], [2]])
> num_classes = 3
> out = Dense(num_classes, activation="softmax", trainable=True)(deepFM_embed)
> model.compile(loss='categorical_crossentropy', optimizer='adam')
> y = to_categorical(Y)
> model.fit(X, y, epochs=1, batch_size = 3)
> 
> b)
> Y = np.array([[0], [1], [2]])
> num_classes = 3
> out = Dense(num_classes, activation="softmax", trainable=True)(deepFM_embed)
> model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
> model.fit(X, Y, epochs=1, batch_size = 3)

This cause error too:
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by mfulford** [comment]
I updated deepFM_keras.py yesteday. Try with the latest version and I think it should work.

**Comment by EagleYing** [comment]
> I updated deepFM_keras.py yesteday. Try with the latest version and I think it should work.

It worked~ Thanks.
Is the loss_function problem or just the version?
